name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Deploy the website to gh-pages
        run: |
          npm install
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions"
          git remote set-url origin https://${{ github.token }}@github.com/${{ github.repository }}.git
          npm run deploy

